
hostname Router-Core-Principal
enable password 7 0831071B10121D
ntp server pool.ntp.org
!
ip ssh version 2
!
interface GigabitEthernet0/1
 ip address 10.0.0.1 255.255.255.0
 no shutdown
!
ip https server
!
banner motd cisco_router_7200_v12.4_propiedad_privada
!
logging host 192.168.1.50
!
line vty 0 4
 exec-timeout 5 0
 login local
 access-class 10 in
 transport input ssh
!
snmp-server community public RO
snmp-server community private RW
!

#What's wrong here?

#It has an SSH version 1 IP address (Outdated cryptography 🔴).

#The `exec-timeout` command is missing in line vty 0 4 (Unattended session exposed 🟡).

#The `motd` banner reveals the router model and the exact IOS version (7200_v12.4) (Information leak 🟡).

#There are no lines starting with `logging host` (It's not sending logs to the SIEM; the SOC is blind 🟡).